// Auto-generated from Libro1.xlsx — DO NOT EDIT MANUALLY

export const POLIGONOS = [
  { codigo: 'RECB0081', nombre: 'Arborizadora Alta' },
  { codigo: 'RECB0161', nombre: 'Arborizadora Alta' },
  { codigo: 'RECB0194', nombre: 'Cerro Seco (SIMA)' },
  { codigo: 'RESC0060', nombre: 'Cantera' },
  { codigo: 'RESC0155', nombre: 'Quebrada Verejones' },
  { codigo: 'RESC0195', nombre: 'Zuque SIMA' },
  { codigo: 'RESC0055', nombre: 'Quebrada Toches' },
  { codigo: 'RESC0305', nombre: 'El Delirio -La Hoya de San Cristóbal' },
  { codigo: 'RESC0142', nombre: 'Futuro Parque Metropolitano La Arboleda' },
  { codigo: 'RESC0054', nombre: 'Serranía del Zuque' },
  { codigo: 'RESF0217', nombre: 'FA07_1 Los Laches' },
  { codigo: 'RESF0068', nombre: 'Monserrate La Calera I' },
  { codigo: 'RESF0058', nombre: 'Monserrate La Calera I' },
  { codigo: 'REUS0316', nombre: 'La Regadera (Usme)' },
  { codigo: 'RESF0216', nombre: 'FA06_1 El Dorado' },
  { codigo: 'REUQ0315', nombre: 'La Serranía Componente 3' },
  { codigo: 'RESF0218', nombre: 'FA08_1 La Peña' },
  { codigo: 'REUQ0305', nombre: 'La serranía Componente 1' },
  { codigo: 'RECP0300', nombre: 'Calasanz' },
  { codigo: 'RECP0299', nombre: 'FA_Mindefensa' },
  { codigo: 'RESC0049', nombre: 'Aguas Claras' },
  { codigo: 'REUQ0302', nombre: 'FA_21_1' },
  { codigo: 'RECB0317', nombre: 'La Regadera (Ciudad Bolivar)' },
  { codigo: 'RESF0323', nombre: 'La Calera Monserrate 1' },
  { codigo: 'REUQ0321', nombre: 'FA_La Serranía' },
] as const

export const ACTIVIDADES = [
  { nombre: '1. Plantación (Siembra)' },
  { nombre: '2. Control Retamo liso' },
  { nombre: '3. Control Chusque y helecho' },
  { nombre: '4. Control Retamo espinoso' },
  { nombre: '5. Control especies forestales exóticas' },
  { nombre: '6. Instalación perchas para aves' },
  { nombre: '7. Instalación cajas nido tipo balcón' },
  { nombre: '8. Instalación refugios para reptiles y anfibios' },
  { nombre: '9. Instalación refugios para murciélagos' },
  { nombre: '10. Instalación madrigueras' },
  { nombre: '11. Georreferenciación arreglos florísticos, Fauna' },
  { nombre: '12. Georreferenciación de áreas de control' },
  { nombre: '13. Ortofoto' },
  { nombre: '14. Primer Mantenimiento' },
  { nombre: '15. Reposición' },
  { nombre: '16. Tutorado' },
  { nombre: '17. Instalación Cercas' },
  { nombre: '3. Control Chusque y helecho marranero' },
  { nombre: '11. Georreferenciación de los arreglos florísticos' },
  { nombre: '12. Georreferenciación áreas y control cambio cobertura' },
  { nombre: '13. Toma de ortoimágenes antes y después' },
  { nombre: '14. Mantenimiento individuo vegetal' },
  { nombre: '15. Replante y enriquecimiento' },
  { nombre: '17. Instalación o adecuación de cercas' },
] as const

// es_corte = true when detalle name contains corte (case-insensitive)
export const DETALLES = [
  { nombre: 'Cal.', es_corte: false },
  { nombre: 'Hidroretenedor.', es_corte: false },
  { nombre: 'Humus.', es_corte: false },
  { nombre: 'Compost.', es_corte: false },
  { nombre: 'Pino.', es_corte: false },
  { nombre: 'Acacia.', es_corte: false },
  { nombre: 'Eucalipto.', es_corte: false },
  { nombre: 'Ahoyado.', es_corte: false },
  { nombre: 'Llenado.', es_corte: false },
  { nombre: 'Individuo plantado.', es_corte: false },
  { nombre: 'Plateo.', es_corte: false },
  { nombre: 'Fertilizacion.', es_corte: false },
  { nombre: 'Fertiriego.', es_corte: false },
  { nombre: 'Control Fitosanitario.', es_corte: false },
  { nombre: 'Riego.', es_corte: false },
  { nombre: 'Elaboracion de fajina', es_corte: false },
  { nombre: 'Corte de flor del retamo', es_corte: true },
  { nombre: 'Corte material somatico', es_corte: true },
  { nombre: 'Destoconado', es_corte: false },
  { nombre: 'Transporte para incineración', es_corte: false },
  { nombre: 'Recolección de material cortado', es_corte: false },
  { nombre: 'Triturado/chipeado y Empaque en globos', es_corte: false },
  { nombre: 'Trazado de los diseños establecidos', es_corte: false },
] as const

export function esCorteDetalle(detNombre: string): boolean {
  return detNombre.toLowerCase().includes('corte')
}
